project:
  type: "website"


# bibliography: "references.bib"


website:
  title: "Presentation: Myself"
  repo-url: &repo-url "https://github.com/mfisher87/presentation-self"
  repo-actions: ["edit", "issue"]
