[project]
name = "presentation-self"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
quarto = "=1.4.550"
pre-commit = "*"
